---
- name: configure the Brightbox APT repository
  apt_repository: repo=ppa:brightbox/ruby-ng
  tags: packages

- name: install system dependencies
  apt: >
    name={{ item }}
    update_cache=yes
  with_items:
    - git
    - openssh-server
    - ruby2.1
    - ruby2.1-dev
    - build-essential
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - libpq-dev
    - python-docutils
    - cmake
    - ruby-pg
  tags: packages

- name: install bundler
  gem: >
    name=bundler
    user_install=no
  tags: packages

- name: create system group
  group: >
    name={{ gitlab_group }}
    system=yes
  tags: accounts

- name: create system user
  user: >
    name={{ gitlab_user }}
    group={{ gitlab_group }}
    groups=redis
    append=yes
    home={{ gitlab_user_home }}
    createhome=yes
    shell=/bin/bash
    system=yes
  tags: accounts

- name: prepare directories
  file: >
    state=directory
    path={{ item.path }}
    owner={{ item.owner | default(gitlab_user) }}
    group={{ item.group | default(gitlab_group) }}
    mode={{ item.mode | default('0755') }}
  with_items:
    - { path: "{{ gitlab_base_dir }}" }
    - { path: "{{ gitlab_shell_dir }}" }
    - { path: "{{ gitlab_logs_dir }}" }
    - { path: "{{ gitlab_temp_dir }}", mode: '0700' }
    - { path: "{{ gitlab_conf_dir }}", owner: 'root', group: 'root' }
    - { path: "{{ gitlab_repos_dir }}", mode: '02770' }
    - { path: "{{ gitlab_satellites_dir }}", mode: '0750' }
    - { path: "{{ gitlab_user_home }}/.ssh" }

- name: make symlinks to default locations
  file: >
    state=link
    src={{ item.src }}
    dest={{ item.dest }}
    force=yes
  with_items:
    - { src: "{{ gitlab_logs_dir }}", dest: "{{ gitlab_base_dir }}/log" }
    - { src: "{{ gitlab_temp_dir }}", dest: "{{ gitlab_base_dir }}/tmp" }

- name: install upstart job configs
  template: >
    src=upstart/{{ item }}.j2
    dest=/etc/init/{{ item }}
    owner=root group=root mode=0644
  with_items:
    - gitlab.conf
    - gitlab-sidekiq.conf
    - gitlab-web.conf
  notify: restart gitlab
  tags: [ install, config ]

- include: install_shell.yml
  sudo: yes
  sudo_user: "{{ gitlab_user }}"

- include: install_gitlab.yml
  sudo: yes
  sudo_user: "{{ gitlab_user }}"
