---
# TODO: This rake task doesn't work alone...
#- name: backup database
#  command: >
#    bundle exec rake gitlab:backup:db:create RAILS_ENV=production
#    chdir={{ gitlab_base_dir }}

- name: stop gitlab
  sudo_user: root
  service: >
    name=gitlab
    state=stopped

- name: run bundle install (this will take few minutes)
  command: >
    bundle install {{ gitlab_bundle_install_opts }}
    chdir={{ gitlab_base_dir }}

- name: migrate database
  command: >
    bundle exec rake db:migrate RAILS_ENV=production
    chdir={{ gitlab_base_dir }}
  notify: restart gitlab

- name: clean and precompile assets (this will take few minutes)
  command: >
    bundle exec rake assets:clean assets:precompile RAILS_ENV=production
    chdir={{ gitlab_base_dir }}
  notify: restart gitlab

- name: clean gitlab cache
  command: >
    bundle exec rake cache:clear RAILS_ENV=production
    chdir={{ gitlab_base_dir }}


- name: (re)link hooks in repositories
  command: >
    {{ gitlab_shell_dir }}/bin/create-hooks

- name: fix command paths in authorized_keys file
  replace: >
    dest={{ gitlab_user_home }}/.ssh/authorized_keys
    regexp='^command="[^ "]+'
    replace='command="{{ gitlab_shell_dir }}/bin/gitlab-shell'
    backup=yes
